kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.3
          args:
          - --providers.kubernetescrd
          - --entrypoints.web.address=:8000
          - --entrypoints.websecure.address=:4443
          - --api.insecure
          - --certificatesresolvers.le.acme.email=masuperadresse@monmail.com
          - --certificatesresolvers.le.acme.storage=/cert/acme.json
          - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web  
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
          volumeMounts:
          - mountPath: "/cert/"
            name: cert 
      volumes:
      - name: cert
        persistentVolumeClaim:
          claimName: cert-pvc
