apiVersion: v1
kind: Service
metadata:
 name: traefik-web-ui
spec:
 selector:
   app: traefik
 ports:
 - port: 8080
   name: api
---
apiVersion: v1
kind: Service
metadata:
 name: traefik-web
spec:
 selector:
   app: traefik
 ports:
 - port: 443
   targetPort: 4443
   name: websecure
 - port: 80
   targetPort: 8000
   name: web
 type: LoadBalancer
